matrix:
  include:
    - os: linux
      sudo: false
      dist: precise
      language: node_js
      node_js: 4
      env: TYPE="docker precise"
    - os: linux
      sudo: false
      dist: trusty
      language: node_js
      node_js: 4
      env: TYPE="docker trusty"
    - os: linux
      sudo: required
      dist: trusty
      language: node_js
      node_js: 4
      env: TYPE="legacy trusty"
    - os: osx
      language: node_js
      node_js: 4
      env: TYPE="osx"

before_install:
- echo "before install"

install:
- env
- echo "install"

before_script:
- echo "before_script"

script:
- echo "script"
- node -e "console.log(require('os').cpus().length)"
- node -e "console.log(require('os').cpus())"

after_success:
- if [ $? != 0 ]; then echo 'failed'; else echo 'worked'; fi
- echo "after_success"
