language: cpp

sudo: false

git:
  depth: 1

before_install:
- git clone https://github.com/mapbox/mapbox-studio.git
- cd mapbox-studio
- gem install bundle
- bundle install --path .bundle
- bundle exec jekyll build --config=_config.test.yml --destination=_site-test

install:
- env
- echo "install"

before_script:
- echo "before_script"

script:
- echo "script"

after_success:
- if [ $? != 0 ]; then echo 'failed'; else echo 'worked'; fi
- echo "after_success"
