language: node_js

matrix:
  include:
    - os: linux
      sudo: false
      node_js: 4
      dist: trusty
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libgles2-mesa', 'libegl1-mesa' ]
    - os: linux
      sudo: required
      node_js: 4
      dist: xenial
      before_install:
        - sudo apt-get install -y libstdc++6 libgles2-mesa libegl1-mesa

install:
 - npm install

script:
 - node -e "console.log(require.resolve('@mapbox/mapbox-gl-native'))"
 - node -e "require('@mapbox/mapbox-gl-native')"
