language: node_js

matrix:
  include:
     # Clang tidy build
    - os: linux
      sudo: false
      node_js: 4
      dist: xenial


install:
 - npm install
 - node -e "console.log(require.resolve('@mapbox/mapbox-gl-native'))" || true
 - node -e "require('@mapbox/mapbox-gl-native')" || true
