sudo: false

# http://docs.travis-ci.com/user/apt/
addons:
  apt:
    sources:
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

install:
 - true

before_script:
 - true

script:
 - true
