language: cpp

sudo: false

git:
  depth: 1

addons:
  postgresql: "9.3"

before_install:
# do we have gdal installed already due to postgres/postgis?
- which ogr2ogr || echo "no ogr2ogr yet installed"
- which gdalinfo || echo "no gdalinfo yet installed"

install:
# install mason
- git clone --depth 1 https://github.com/mapbox/mason.git .mason; export MASON_DIR="$(pwd)/.mason"; export PATH="$(pwd)/.mason":${PATH};

before_script:
# install gdal with mason locally
- mason install gdal 1.11.1
# link gdal to ./mason_packages/.link
- mason install gdal 1.11.1
# configure GDAL_DATA so projection data lookup works
- export GDAL_DATA=$(pwd)/mason_packages/.link/share/gdal
# put Mason ./bin on PATH
- export PATH=$(pwd)/mason_packages/.link/bin:${PATH}

script:
# Test that gdalinfo works
- gdalinfo --version
- which gdalinfo
# ensure it is "standalone" and does link to anything non-portable
- ldd $(which gdalinfo)
- ogr2ogr --version
- which ogr2ogr
# ensure it is "standalone" and does link to anything non-portable
- ldd $(which ogr2ogr)

after_success:
- if [ $? != 0 ]; then echo 'failed'; else echo 'worked'; fi
- echo "after_success"
