#language: cpp
language: objective-c

sudo: false

git:
  depth: 1

before_install:
- set -e
- set -o pipefail
- echo "before install"
- time brew remove --force $(brew list)

install:
- env
- echo ${TRAVIS_PULL_REQUEST}
- echo ${TRAVIS_BRANCH}
- echo ${TRAVIS_BUILD_ID}
- echo ${TRAVIS_COMMIT}
- git log --format=%B --no-merges -n 1
- git show -s --format=%B ${TRAVIS_COMMIT}
- git show -s --format=%B
- echo "install"

before_script:
- echo "before_script"

script:
- echo "script"

after_success:
- if [ $? != 0 ]; then echo 'failed'; else echo 'worked'; fi
- echo "after_success"
