#language: cpp
language: objective-c

sudo: false

git:
  depth: 1

before_install:
#- set -e
#- set -o pipefail
- echo "before install"

install:
#- env
- COMMIT1=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
- COMMIT2=$(git show -s --format=%B | tr -d '\n')
- echo "${COMMIT1} - ${COMMIT2}"
- |
  if [[ ${COMMIT1} != ${COMMIT2} ]]; then
     echo "Yes, the two commits are different - looks like merge commit"
  else
     echo "No, commits are identical - does not look like a merge commit"
  fi
- |
  if [[ ${COMMIT2} =~ "Merge " ]] && [[ ${COMMIT2} =~ " into " ]]; then
     echo "Yes, this looks like a merge commit"
  else
     echo "No this does not look like a merge commit"
  fi
- scripts/is_pr_merge.sh
- |
  if [[ $(./scripts/is_pr_merge.sh) ]]; then
     echo "yes, via script"
  else
     echo "no, via script"
  fi
- |
  if [[ $(./scripts/is_pr_merge.sh) == true ]]; then
     echo "yes 2, via script"
  else
     echo "no 2, via script"
  fi

before_script:
- echo "before_script"

script:
- echo "script"

after_success:
- if [ $? != 0 ]; then echo 'failed'; else echo 'worked'; fi
- echo "after_success"
