language: node_js

matrix:
  include:
     # Clang tidy build
    - os: linux
      sudo: false
      node_js: 4
      dist: trusty

# enable c++11/14 builds
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-6', 'libgles2-mesa', 'libegl1-mesa' ]

install:
 - npm install

script:
 - node -e "console.log(require.resolve('@mapbox/mapbox-gl-native'))"
 - node -e "require('@mapbox/mapbox-gl-native')"
