#language: cpp
language: objective-c

sudo: false

git:
  depth: 1

before_install:
- set -e
- set -o pipefail
- echo "before install"
- time brew remove --force $(brew list)

install:
- env
- echo "install"

before_script:
- echo "before_script"

script:
- echo "script"

after_success:
- if [ $? != 0 ]; then echo 'failed'; else echo 'worked'; fi
- echo "after_success"
